#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "goweb"
name = "Goweb"
description.en = "Go web app"
description.fr = "Go web app"

version = "1.0~ynh1"

maintainers = [""]

[upstream]
license = "free"
code = "https://git.ericandmarie.fr/eric/goweb/"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/goweb"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    url = "https://github.com/ericgaspar/goweb/releases/download/0.1/goweb"
    sha256 = "e63acae8a1e329cdd357a57203cf7fc0b58d6b84ae9049461bbf340df6a4410e"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9090
    