#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "goweb"
name = "Goweb"
description.en = "Go web app"
description.fr = "Go web app"

version = "1.0~ynh1"

maintainers = [""]

[upstream]
license = "free" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://example.com"
demo = "https://demo.example.com"
code = "https://some.forge.com/example/example"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/goweb"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://git.ericandmarie.fr/eric/goweb/-/archive/main/goweb-main.zip"
    sha256 = "6e1ff44a6c3b364507290657b741f96257cc625a4b2fbd38494cbb381d7e091b"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 9090